defmodule ViewNinjasWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :viewninjas

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_viewninjas_key",
    signing_salt: "8Ly2CEyM",
    same_site: "Lax"
  ]

  # peer_data/x_headers let a LiveView rate-limit by client IP, the same way a
  # controller reads conn.remote_ip; user_agent/uri are the device class and the
  # entry URL a first-party page view records (scope.md §13; build-plan.md M6).
  #
  # These are bare keys: Phoenix treats a `key: value` pair here as *custom*
  # connect_info, so `user_agent: true` would hand the view the literal `true`
  # instead of the header.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [
        :peer_data,
        :x_headers,
        :user_agent,
        :uri,
        session: @session_options
      ]
    ],
    longpoll: [
      connect_info: [
        :peer_data,
        :x_headers,
        :user_agent,
        :uri,
        session: @session_options
      ]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :viewninjas,
    gzip: not code_reloading?,
    only: ViewNinjasWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :viewninjas
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    # Keeps the exact bytes so a signed webhook can be verified (scope.md §8).
    body_reader: {ViewNinjasWeb.BodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # One address per page: a request for a path with a trailing slash is
  # redirected to the path without it, before the router has to find a route
  # for a URL that would otherwise 404.
  plug ViewNinjasWeb.Plugs.TrailingSlash

  plug ViewNinjasWeb.Router
end
